config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/show'
  resources :training_records
  get 'training_records/download/:id', to: 'training_records#download'

  devise_for :users #, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/training_record.rb
class TrainingRecord < ApplicationRecord
  mount_uploader :video, VideoUploader
  validates :video, :presence => true
  has_one :user

  def build_video_url
    "https://s3-ap-northeast-1.amazonaws.com/muscle-checker/#{TrainingRecord.last.video.file.path}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :training_records

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth["provider"], uid: auth["uid"]) do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
      end
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

        if @user.persisted?
            sign_in_and_redirect @user
        else
            session["devise.user_attributes"] = @user.attributes
            redirect_to new_user_registration_url
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @training_record = current_user.training_records.new
    @training_record.part = 'push_up'
  end

  def show
  end
end

app/controllers/training_records_controller.rb
class TrainingRecordsController < ApplicationController
  before_action :set_training_record, only: [:show, :edit, :update, :destroy, :download]

  # GET /training_records
  # GET /training_records.json
  def index
    @training_records = TrainingRecord.all
  end

  # GET /training_records/1
  # GET /training_records/1.json
  def show
  end

  # GET /training_records/new
  def new
    @training_record = TrainingRecord.new
  end

  # GET /training_records/1/edit
  def edit
  end

  # POST /training_records
  # POST /training_records.json
  def create
    @training_record = current_user.training_records.new(training_record_params)
    @training_record.part = 'push_up' unless @training_record.part.present?

    respond_to do |format|
      if @training_record.save
        format.html { redirect_to @training_record, notice: 'Training record was successfully created.' }
        format.json { render :show, status: :created, location: @training_record }
      else
        format.html { render :new }
        format.json { render json: @training_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /training_records/1
  # PATCH/PUT /training_records/1.json
  def update
    respond_to do |format|
      if @training_record.update(training_record_params)
        format.html { redirect_to @training_record, notice: 'Training record was successfully updated.' }
        format.json { render :show, status: :ok, location: @training_record }
      else
        format.html { render :edit }
        format.json { render json: @training_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /training_records/1
  # DELETE /training_records/1.json
  def destroy
    @training_record.destroy
    respond_to do |format|
      format.html { redirect_to training_records_url, notice: 'Training record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    # ref: https://github.com/carrierwaveuploader/carrierwave#activerecord
    filepath = @training_record.video.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @training_record.video_identifier, :length => stat.size)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training_record
      @training_record = TrainingRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_record_params
      params.require(:training_record).permit(:title, :video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/training_records_helper.rb
module TrainingRecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuscleChecker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <header>
            <nav>
                <% if user_signed_in? %>
                <strong><%= link_to current_user.username, pages_show_path %></strong>
                <%= link_to 'プロフィール変更', edit_user_registration_path %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
                <% end %>
            </nav>
        </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: training_record, local: true) do |form| %>
  <% if training_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training_record.errors.count, "error") %> prohibited this training_record from being saved:</h2>

      <ul>
      <% training_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video, :accept => 'video/*' %>
  </div>

  <div class="actions">
    <%= form.submit '解析スタート', :class => "moveUp-wrap moveUp" %>
  </div>
<% end %>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./style.css">
    <title>Muscle form checker</title>
  </head>
  <body>
    <header>
      <div class="header-wrap">
        <!-- <a class="hdr-icon-home" href="#"></a> -->
        <h1>Muscle form checker</h1>
        <!-- <a class="hdr-icon-menu" href="#"></a> -->
      </div>
    </header>
    <div class="mv-wrap">
      <img class="mv" src="../img/mv.png" alt=" Muscle Form Checker">
    </div>
    <div class="article">
      <p class="article-title"><span>Muscle form checker</span>とは</p>
      <p class="article-txt">ここにトレーニングの説明が入ります。腕立てだったら曲げてねとか顔は1m先を見てねとか。あと10回3セットとか。3、4行の説明がいいのかなあ。あああああああ</p>
    </div>

    <div class="container">
<!-- /* ******************************** */ -->
    <!-- トレーニングの練習メニューを決める画面 -->
<!-- /* ******************************** */ -->
    <!-- コンテンツ -->
      <div class="conts">
        <div class="menuListItem">
          <p class="topic">Training Menu</p>
          <p class="subtopic">トレーニングメニュー</p>
          <div class="menuList">
            <ul>
              <li><a href="#" class="menuList-close">腕立て伏せ</a></li>
              <li><a href="#" class="menuList-close">スクワット</a></li>
              <li>
                <div class="menuList-open">
                  <a href="#" class="menuList-open-title">腕立て伏せ</a>
                  <div class="movebox"></div>
                  <p class="txt">ここにトレーニングの説明が入ります。腕立てだったら曲げてねとか顔は1m先を見てねとか。あと10回3セットとか。3、4行の説明がいいのかなあ。あああああああ</p>
                  <%= render 'form', training_record: @training_record %>
                  <a class="uploadBtn" href="#">ファイルをアップロード</a>
                  <a class="anaBtn" href="#"><span>フォームを分析する</span></a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>


<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/training_records/_form.html.erb
<%= form_with(model: training_record, local: true) do |form| %>
  <% if training_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training_record.errors.count, "error") %> prohibited this training_record from being saved:</h2>

      <ul>
      <% training_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video, :accept => 'video/*' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/training_records/edit.html.erb
<h1>Editing Training Record</h1>

<%= render 'form', training_record: @training_record %>

<%= link_to 'Show', @training_record %> |
<%= link_to 'Back', training_records_path %>

app/views/training_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Training Records</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @training_records.each do |training_record| %>
      <tr>
        <td><%= training_record.title %></td>
        <td><%= training_record.video %></td>
        <td><%= link_to 'Show', training_record %></td>
        <td><%= link_to 'Edit', edit_training_record_path(training_record) %></td>
        <td><%= link_to 'Destroy', training_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training Record', new_training_record_path %>

app/views/training_records/new.html.erb
<%= stylesheet_link_tag "training_records_new", :media => "all" %>

<h1>New Training Record</h1>

<%= render 'form', training_record: @training_record %>

<%= link_to 'Back', training_records_path %>

app/views/training_records/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./score.css">
    <title>Muscle form checker</title>
  </head>
  <body>
    <header>
      <div class="header-wrap">
        <!-- <a class="hdr-icon-home" href="#"></a> -->
        <h1>Muscle form checker</h1>
        <!-- <a class="hdr-icon-menu" href="#"></a> -->
      </div>
    </header>

    <div class="container">
<!-- /* ******************************** */ -->
    <!-- トレーニングの練習メニューを決める画面 -->
<!-- /* ******************************** */ -->
    <!-- コンテンツ -->
      <div class="conts">
        <div class="menuListItem">
          <p class="topic">Training Menu</p>
          <p class="subtopic">トレーニングメニュー</p>
          <div class="menuList">
            <ul>
              <li><a href="#" class="menuList-close">腕立て伏せ</a></li>
              <li><a href="#" class="menuList-close">スクワット</a></li>
              <li>
                <div class="menuList-open">
                  <a href="#" class="menuList-open-title">腕立て伏せ</a>
                  <div class="movebox"></div>
                  <p class="txt">ここにトレーニングの説明が入ります。腕立てだったら曲げてねとか顔は1m先を見てねとか。あと10回3セットとか。3、4行の説明がいいのかなあ。あああああああ</p>
                  <a class="uploadBtn" href="#">ファイルをアップロード</a>
                  <a class="anaBtn" href="#"><span>フォームを分析する</span></a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>


<%= stylesheet_link_tag "training_records_show", :media => "all" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @training_record.title %>
</p>

<p>
  <strong>Video:</strong>
  <%= @training_record.video %>
</p>

<%= link_to 'Edit', edit_training_record_path(@training_record) %> |
<%= link_to 'Back', training_records_path %>